### ISSUE TITLE
Error: This does not seem to be a WordPress install.

### ISSUE THREAD

**Issue by connor11528** [collizo4sky/wp-meta-verify#2]
I have a plugin that is one php file that I'd like to write tests for. I've installed everything and then run:

```
$ wp scaffold plugin-tests my-plugin-name
Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.
```

Is there a way to test a plugin without having a wordpress install? Do you keep the wordpress site in a directory next to the directory for this plugin?

Thank you!

**Comment by w3guy** [comment]
You will need to have a WordPress install and the plugin repo inside wp-content/plugins
